# -*- coding: utf-8 -*-
"""Sorteo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iW1s6E6emxpdWFf22ZyhyHUCh-EQFT5J
"""

import random

def sorteo():
    # Lista fija de valores para el sorteo
    valores = [
        "Real Madrid",
        "FC Barcelona",
        "Atlético de Madrid",
        "Manchester United",
        "Bayern Múnich",
        "Juventus",
        "Paris Saint-Germain",
        "Liverpool"
    ]

    print("¡Bienvenido al sorteo!\n")

    # Bucle: mientras queden valores disponibles
    while valores:
        nombre = input("Ingrese tu nombre (o presiona Enter para terminar): ").strip()
        if not nombre:
            print("Terminando el sorteo…")
            break

        # Elegir y eliminar el valor asignado
        asignado = random.choice(valores)
        valores.remove(asignado)

        print(f"🎉 ¡Felicidades, {nombre}! Te tocó: {asignado}")
        print(f"Quedan {len(valores)} valor(es) disponibles.\n")

        if not valores:
            print("Se han agotado todos los valores del sorteo.")
            break

        # Preguntar si quieren sortear a otra persona
        seguir = input("¿Deseas sortear a otra persona? (Si/No): ").strip().lower()
        if seguir != 'Si':
            print("Sorteo finalizado.")
            break

if __name__ == "__main__":
    sorteo()